# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql+mysqlconnector"  # <-- THIS IS THE FIX

host = "72.60.218.98"       # e.g., "localhost" or "127.0.0.1"
port = 3306
database = "exceldata"
username = "fastapi_user"
password = "StrongPass123!"


